- name: copy bashrc template to {{ inventory_hostname }}
  ansible.builtin.template:
    src: bashrc.j2
    dest: /home/{{ ansible_user }}/.bashrc
    owner: {{ ansible_user }}
    group: {{ ansible_user }}
    mode: '0644'
