#- name: check actions
#  ansible.builtin.fail:
#    msg: Invalid action given {{ apt_action }}
#  when: not apt_action in valid_apt_actions
- debug:
    msg: "apt update cache {{ update }}"
- name: update cache
  become: yes
  become_method: sudo
  ansible.builtin.apt:
    update_cache: yes
  when: update
- name: install packages
  become: yes
  become_method: sudo
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ apt_packages }}"
  when: install