---
- name: Raspberry Pi4 cluster base line
  gather_facts: true
  hosts:
    - master
  vars:
    dry_run: true
    global_vars.systemd.units:
      - networking
      - NetworkManager
      - handle_external_hdds
      - udisks2
      - zramswap
      - dphys-swapfile
  tasks:
    - name: Os detection
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop:
        - "OS detected: {{ ansible_facts.distribution + ' ' + ansible_facts.distribution_version }}"

    - name: Rollout
      ansible.builtin.include_role:
        name: baseline

    - name: Systemd
      ansible.builtin.include_role:
        name: systemd
        defaults_from: main.yaml
      loop: "{{ global_vars.systemd_unit }}"
      vars:
        unit: "{{ item }}"
...